version: '3.8'

services:
  mirai-api-server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: mirai-api-server-prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HUBSPOT_API_KEY=${HUBSPOT_API_KEY}
      - HUBSPOT_ID=${HUBSPOT_ID}
    env_file:
      - .env.prod
    volumes:
      - ./logs:/app/logs
    networks:
      - mirai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: mirai-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - mirai-api-server
    networks:
      - mirai-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mirai-network:
    driver: bridge

volumes:
  logs:
    driver: local
